name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-exponential-smoothing-predictor:
    name: Build and push exponential-smoothing-predictor
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: exponential-smoothing-predictor
      image-name: exponential-smoothing-predictor
    secrets: inherit
